### ISSUE TITLE
GET response with binary file in body

### ISSUE THREAD

**Issue by LuongTanDat** [ipkn/crow#399]
In my code, it have a `GET` method, and the `GET` will response a binary file on body of response, but I found that constructor of `crow::response` only accept std::string, not for `unsigned char` (because value of bytes are in range 0-255, so use std::string is not suitable).
How can I implement the program will receive GET query and get binary file on response with `crow` library?

**Comment by The-EDev** [comment]
Hi @LuongTanDat 
Unfortunately this repository has been abandoned for 4 years, I would recommend you use https://github.com/CrowCpp/Crow instead.

With that being said, `std::string` and `unsigned char*` should be able to hold the same data (since in binary `-1` and `128` are both `1000 0000`). maybe you can use cast the data into a `char*` and use that to generate an `std::string`.

**Comment by LuongTanDat** [comment]
@The-EDev Many thanks
